### ISSUE TITLE
Hi, i am testing the script for KRACK vulnerability

### ISSUE THREAD

**Issue by angelocarb** [domienschepers/wifi-framework#1]
I am on my Kali Linux VM and i obtained this situation when i try to create an AP and after a client that connect to this AP. 
What could be the problem?

I am follow instructions on the repo, but when i try to connect to "testnetwork" with the passhprase i obtained this error that are attached below:

![image](https://user-images.githubusercontent.com/40144366/211178060-a6081b17-da77-4632-9618-ed2e9bea5b7d.png)
![image](https://user-images.githubusercontent.com/40144366/211178069-10afd8c7-a78b-41ba-8603-529f5c05dd1f.png)

**Comment by domienschepers** [comment]
It would seem that your client is not vulnerable to the attack, or is not generating any data traffic to verify this. To quickly generate data traffic you could use the `ping` command using the respective interface (see the [All-Zero Key Reinstallation Vulnerability](https://github.com/domienschepers/wifi-framework/blob/master/docs/EXAMPLES.md#all-zero-key-reinstallation-vulnerability) example).

To test a client (supplicant) that is known to be vulnerable you can follow the instruction for the [All-Zero Key Reinstallation Vulnerability](https://github.com/domienschepers/wifi-framework/blob/master/docs/EXAMPLES.md#all-zero-key-reinstallation-vulnerability) example and explicitly specify a vulnerable version. This way you can verify that the test case works as expected.

If that is not helpful, what is the command and output for your client station? The first few lines of output will state which version of `wpa_supplicant` is being used.

**Comment by 500BadRequestt** [comment]
Hi Domien, thanks for the answer.

I am testing exactly "example-krack-zero-key" for a demonstration, so i have Kali linux 2022 that have a wired connection with my host OS (Windows 11). 

For your framework it is not necessary to have an external wifi dongle USB, right ? 

For what concern wpa_supplicant, where can i search a vulnerable version that compile and work ? 

And how can i integrate the source file of vulnerable wpa_supplicant in your framework code ?

Because i have a lot of compiling error probably because they are now obsolete versions.

Thanks!

**Comment by angelocarb** [comment]
Hi Domien, thanks for the answer.

I am testing exactly "example-krack-zero-key" for a demonstration, so i
have Kali linux 2022 that have a wired connection with my host OS (Windows
11).

For your framework it is not necessary to have an external wifi dongle USB,
right ?

For what concern wpa_supplicant, where can i search a vulnerable version
that compile and work ?

And how can i integrate the source file of vulnerable wpa_supplicant in
your framework code ?

Because i have a lot of compiling error probably because they are now
obsolete versions.

Thanks!

Il giorno sab 14 gen 2023 alle ore 23:18 domienschepers <
***@***.***> ha scritto:

**Comment by domienschepers** [comment]
> For your framework it is not necessary to have an external wifi dongle USB, right ?

That is correct. You can use `mac80211_hwsim` to simulate radios, which is what we do in our [setup-hwsim.sh](https://github.com/domienschepers/wifi-framework/blob/master/setup/setup-hwsim.sh) script.

> For what concern wpa_supplicant, where can i search a vulnerable version that compile and work ?

The easiest would be to try out Version 2.5 as used in the [All-Zero Key Reinstallation Vulnerability](https://github.com/domienschepers/wifi-framework/blob/master/docs/EXAMPLES.md#all-zero-key-reinstallation-vulnerability) example.

You can find all releases [here](https://w1.fi/cgit/hostap/) and compile them from source.

**Comment by 500BadRequestt** [comment]
Hi domien,
i have some problems. I take from your URL https://w1.fi/cgit/hostap/ the **hostap_2_5** version because this is the vulnerable version. 

I am on a **Kali Linux 2022** machine

I copied source code https://github.com/domienschepers/wifi-framework/blob/master/docs/EXAMPLES.md#all-zero-key-reinstallation-vulnerability for example-crack-zero-key test in a new python file named "**example-crack-zero-key.py**" and i put this file in the same directory with others test file in your repo.

1) I copied the entire folder(hostap_2_5) in your repo that i cloned (i copied the folder into the DEPENDENCIES folder)
2) I modified the BUILD.SH because by default set hostap_2_10, i replace this string with hostap_2_5
3) I installed all dependencies 
apt-get update
apt-get install git make gcc python3-venv net-tools
apt-get install libdbus-1-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev libssl-dev 
4) i launched **./setup.sh but** i received an error, this is a problem because if i not compile hostap_2_5 i can't execute the example-crack-zero-key test !

This is the error the receive when i launched **./setup.sh** after that i copied the **hostap_2_5** folder and modified the **build.sh** file: (i tried to uncomment a row **CONFIG_LIBNL32=yes** that i found on the web at this URL, but without results: https://askubuntu.com/questions/617973/fatal-error-netlink-genl-genl-h-no-such-file-or-directory

![image](https://user-images.githubusercontent.com/40144366/219420632-56c0006d-31c9-4b67-9339-6e79c3fc8bd0.png)

This is my organization with the hostap_2_5 added:

![image](https://user-images.githubusercontent.com/40144366/219421061-86e0fd6c-bdc4-4422-8124-7b9cf69827ba.png)

and this is the row that i modified in BUILD.SH:

![image](https://user-images.githubusercontent.com/40144366/219421314-f795fd8a-8c73-4a05-8fca-7c8e360d52fe.png)

**Comment by domienschepers** [comment]
This seems to be a problem with compiling an older hostap version on a recent kernel. To narrow down the problem you can try to compile the default configuration for hostap and check which problems come up. For example, copy hostap to a temporary folder and go directly into `hostap_2_5/hostapd` and `hostap_2_5/wpa_supplicant` and run the commands:
```
cp defconfig .config
make clean
make
```

If all dependencies are working this should compile hostap using its default configuration.

Otherwise an easier solution may be to use an older Kali image to act as the vulnerable client. In this case you can still use the framework and run the test case using the latest hostap version. Then, you can use the older Kali machine to install the vulnerable wpa_supplicant version and manually connect the client to the AP.

If this is not helpful let me know which exact Kali version you are using and I'll download it to check.

**Comment by 500BadRequestt** [comment]
Hi domien,
thanks for the answer. BTW i am using this version of kali linux

![image](https://user-images.githubusercontent.com/40144366/219719340-847f3477-261c-44ab-8764-de253d54abdb.png)

**Comment by 500BadRequestt** [comment]
I tried with compiling with the commands:

cp defconfig .config
make clean
make

but i receive same errors. 
I didn't understand the second point:
1) I must to download an older version of Kali
2) i must to clone your repo in this older OS
and after ?

**Comment by domienschepers** [comment]
The vulnerable hostap version was released many years ago and therefore it may not (easily) work anymore on modern kernels. Since this particular test case will set itself up as an access point in order to evaluate a client, you can still run the framework and test case on your modern system. Then in order to test a client, in this case the vulnerable wpa_supplicant version, you can set up the client using an older Kali machine which consequently has an older kernel and hopefully supports the older hostap version without much problems. Once everything is set up, you can use your client to connect to the access point and the test case will start running automatically.

**Comment by 500BadRequestt** [comment]
Yes yes, but all in one machine .. i want to say ..
i am installing kali 2016 ... i run access point on kali 2016 and when compare the name of network on the screen i manually connect to this access point ? 

But i don't launch the client from the script, but only the script for the AP ?

**Comment by 500BadRequestt** [comment]
@domienschepers in anycase do you have a contact (telegram or other) where we can talk faster and in a real time while i try to set up the environment ? If yes, what it your local timezone ? 

Thank you very much !

**Comment by vanhoefm** [comment]
To give an alternative idea: another approach is to patch the latest hostap to make it vulnerable to the PTK key reinstallation. I've created an example patch that _should_ do this: https://gist.github.com/vanhoefm/c78bb12171c5785e423ccd589a4deeeb I haven't tested that patch though. Hopefully domienschepers can help you further.

**Comment by 500BadRequestt** [comment]
@vanhoefm thank you very much but i need to test exactly the example-krack-zero-key-test with this repo, it's a request that i must to respect ... thanks ! 
i am waiting for @domienschepers answers in anycase thanks !

**Comment by 500BadRequestt** [comment]
in anycase @domienschepers i receive the same errors on a KALI 2016 OS:

![image](https://user-images.githubusercontent.com/40144366/219791828-56a5ada5-bd2c-4366-9e5c-77fff7bc92c8.png)

**Comment by 500BadRequestt** [comment]
Hi @domienschepers do you have some news ? 

Thanks !

**Comment by domienschepers** [comment]
The quickest way to get a vulnerable supplicant working is to install [Ubuntu 16.04.7 LTS](https://releases.ubuntu.com/16.04/) and [hostap 2.5](https://w1.fi/cgit/hostap/).

Once Ubuntu is running you will have to install:
```
apt-get install libssl-dev libnl-3-dev libnl-genl-3-dev
```

Then download [hostap](https://w1.fi/cgit/hostap/) and uncomment `CONFIG_LIBNL32=y` in the wpa_supplicant configuration file (.config).

Run make and it should execute without problems. Verify the supplicant version using:
```
./wpa_supplicant -v
``` 

Now, in order to run the test case, you will have to use both your Kali and Ubuntu machines. 

On your original Kali machine, you can run the framework with the [All-Zero Key Reinstallation Vulnerability](https://github.com/domienschepers/wifi-framework/blob/master/docs/EXAMPLES.md#all-zero-key-reinstallation-vulnerability) test case:
```
./run.py wlan0 example-krack-zero-key
```

This will set up an access point which will evaluate connecting clients (supplicants) for the vulnerability.

On your new Ubuntu machine, you can now connect to the framework's access point:
```
./wpa_supplicant -c supplicant.conf -i wlan0
```

With the appropriate [configuration file](https://github.com/domienschepers/wifi-framework/blob/master/setup/supplicant-wpa2-personal.conf) for this test case.

As the client on the Ubuntu machine starts to connect, the test case will execute.

**Comment by 500BadRequestt** [comment]
i will try with this steps .. but a question ...
Kali (2022) and Ubuntu are on different machines, so i am note sure that the access point it's visible on another machine directly ...
It is more comfortable to test all on Ubuntu without kali linux ?

**Comment by 500BadRequestt** [comment]
so @domienschepers in anycase i followed the steps and i created wpa_supplicant 2.5 binary ... im testing all in a single machine (Ubuntu 16.04 and firs i launched this command to create interface:

**./setup/setup-hwsim.sh 4** -> this work and create 4 interface

 but when i launch this command i obtain:
**./run.py wlan0 example-krack-zero-key**

![image](https://user-images.githubusercontent.com/40144366/219985002-ba0619bc-a76b-4340-8995-0426a093fe87.png)

So i created the file with test in this way:


![image](https://user-images.githubusercontent.com/40144366/219985061-b5d6a15d-d58d-4c51-83e8-c92dbffa093d.png)

In anycase for this command:

**./wpa_supplicant -c supplicant.conf -i wlan0**

i must to replace **supplicant.conf** with **supplicant-wpa2-personal.conf** in the command right ?

**Comment by 500BadRequestt** [comment]
Hi @domienschepers this is my situation:

1) I compiled wpa_supplicant and hostap with make commands successfully.

![image](https://user-images.githubusercontent.com/40144366/220069233-726f4144-81b9-4ae2-9121-7d72ec8c2e38.png)

2) after i create example-krack-zero-key.py file
3) i execute 
./setup/setup-hwsim.sh 2
source setup/venv/bin/activate

4) in the screen you see on the right terminal i want to launch the Access Point but the command don't work with the command **./run.py wlan0 example-krack-zero-key** -> command don't work
5) On the terminal left i want to launch the client with the command **./wpa_supplicant -c /home/angelo/Documenti/wifi-framework/setup/supplicat-wpa2-personal.conf -i wlan0** -> if the command for AP don't work i can't launch this for client

**Comment by 500BadRequestt** [comment]
Hi @domienschepers do you have some news ? 

Thanks!

**Comment by 500BadRequestt** [comment]
@domienschepers i just launch the client (right terminal in the screen) but i don't know why on the left terminal python give me this error and i can't launch the AP ...

![image](https://user-images.githubusercontent.com/40144366/220154141-45a2eb62-e2d4-4f01-8d71-ae2e4772e1ce.png)

I want test all in a single Ubuntu 16.04.7 TLS machine

**Comment by 500BadRequestt** [comment]
@domienschepers have you tried if it's a problem of the repo or virtualenv ? 

Sorry for the questions but i should resolve this problem and execute the test :)

**Comment by 500BadRequestt** [comment]
Hi @domienschepers, on the same VM (kali linux 2022):

1) i lauched **./setup/setup-hwsim 4**

2) i launched the AP with command that you said me -> **./run.py wlan0 example-krack-zero-key** (before running wpa_supplicant executable on this architecture i installed libssl1.0 library.

3) i launched the client with the command that you said me -> **./wpa_supplicant /home/kali/Documents/wifi-framework/setup/supplicant-wpa2-personal.conf -i wlan0**

but i obtain this:

![image](https://user-images.githubusercontent.com/40144366/220588828-d4052db0-3509-4417-be6a-7005b3e1239b.png)

do you have ideas ? @vanhoefm @domienschepers

**Comment by domienschepers** [comment]
You are trying to run the client and access point on the same interface, which does not work. Instead change one of the interfaces (for example, your client using wpa_supplicant) from `wlan0` to `wlan1`. For example:

```
./wpa_supplicant /home/kali/Documents/wifi-framework/setup/supplicant-wpa2-personal.conf -i wlan1
```

Once connected, make sure your client generates some data traffic in order to verify it is vulnerable.

Please note there are [troubleshooting tips](https://github.com/domienschepers/wifi-framework/blob/master/docs/USAGE.md#troubleshooting) in case you experience an issue.

Regarding your earlier issue ('SyntaxError') on Ubuntu 16.04.7 LTS, that is because this Ubuntu version comes with an older Python version which does not support some of the syntax. Therefore the solution would be to upgrade to a more recent version of Python. Though it is recommended to run the framework using a recent operating system.

**Comment by 500BadRequestt** [comment]
hi @domienschepers,

i tried changing interface and testing with troubleshooting tips and i obtained this situation (it seems all frozen):

![image](https://user-images.githubusercontent.com/40144366/220720834-f34cb086-2de2-46d8-a014-719c85afb9ad.png)


I will wait for an answer, thank you very much !

**Comment by 500BadRequestt** [comment]
with the correct interfaces i obtained PONG:

![image](https://user-images.githubusercontent.com/40144366/220723997-03254b1e-474e-4b77-9e12-4b900c9db637.png)

What do you think ?

**Comment by 500BadRequestt** [comment]
so @domienschepers ,

i obtained this situation launching this command after running AP and WPA_SUPPLICANT:
**ping -I wlan1 1.1.1.1**

![image](https://user-images.githubusercontent.com/40144366/220742358-d808ba4b-b87f-47f2-8916-9a10cfceaadf.png)

Do you think that the test it's conclused with success ?

**Comment by domienschepers** [comment]
Indeed, the framework's test case decrypted a data frame (an ARP request in this example) using an all-zero encryption key. 

You have now successfully confirmed that wpa_supplicant (version 2.5) is vulnerable for this specific attack.

**Comment by 500BadRequestt** [comment]
Yes thank you very much for all! 
I tried for curosity to generate another packet but with a supplicant 2.10 and the test don't print nothing because this version it's not vulnerable to this all zero Key reinstallation Attack. Do you confirm this ? 

In anycase i used an AP that use hostap 2.10 but it's not important because the client continues to be vulnerable. Probably i Will test with wpa3 on the client or on the AP and see what the test print (Imagine nothing since wpa3 it's not vulnerable).

So now the test work successfully ! 
@domienschepers

**Comment by domienschepers** [comment]
You are correct, the latest supplicant version is not vulnerable since the issues have been fixed for a while now. And indeed, for this test case you can safely use the latest hostap version since we are testing for vulnerable clients.
